### ISSUE TITLE
installation instructions need adjustment

### ISSUE THREAD

**Issue by dmitris** [yahoo/context-parser#3]
The installation / run instructions currently do not work as given:
```
$ npm install context-parser
context-parser@1.0.0 node_modules/context-parser
└── debug@2.1.1 (ms@0.6.2)
$ ./bin/contextparse /tmp/test.html
-bash: ./bin/contextparse: No such file or directory
```

Should either do ```npm install -g context-parser``` or provide the full path to the binary under node_modules:
```
$ ./node_modules/context-parser/bin/contextparse /tmp/test.html
```

**Comment by neraliu** [comment]
@dmitris, please check if u have time
https://github.com/yahoo/context-parser/pull/22

**Comment by neraliu** [comment]
the README has been updated accordingly
https://github.com/yahoo/context-parser/pull/22
